### ISSUE TITLE
Circuit

### ISSUE THREAD

**Issue by Lumi3011** [ChristophSchranz/ecg_via_raspberrypi#1]
Hello there,

Can you help me with the circuit, because the picture you have in project does not seem to be correct.

Thanks

**Comment by ChristophSchranz** [comment]
Hello Lumi,
the circuit should work this way. However, as I want to keep it as simple as possible, I didn't use the offset potential of the IN126. There are two solutions for that:
1. Switch the + and - electrodes to get the negated signal
2. Put a potentiometer on this contact and set the offset level to get it work properly.

If that doesn't work, can you please describe the problem in detail.

**Comment by ChristophSchranz** [comment]
I've rebuilt the circuit board and you were right, the MCP3208 needs two connections to the ground.
I commited the updated layout (https://github.com/ChristophSchranz/ecg_via_raspberrypi/commit/517865133a92bd77290136628bff4dbfcc6e3bf7)

Thank you for reporting the bug!
